# examples/0001-small-network.toml
[relaychain]
default_image = "docker.io/parity/polkadot:latest"
default_command = "./polkadot"
default_args = [ "-lparachain=debug" ]

chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true



# ./zombienet-macos spawn small-network.toml -p native

[[parachains]]
id = 2040

[parachains.collator]
name = "collator01"
command = "./parachain-polkadex-node"
args = ["-lparachain=debug"]